title: Site

columns:
  left:
    width: 1/2
    sections: 
      listed:
        extends: sections/readings 
        headline: Recent Readings
        status: listed
        limit: 10

  right:
    width: 1/2
    sections:
      pages:
        type: pages
        headline: Recent Meetings
        info: "{{ page.day.toDate('m.d.Y') }}"
        parent: site.find("meetings")
        empty: No events yet
        sortBy: date desc
      info:
        type: pages
        headline: Info & Index
        status: listed
      
    
      