title: Site

columns:
  left:
    width: 1/2
    sections: 
      listed:
        extends: sections/readings 
        headline: Readings
        limit: 10

  right:
    width: 1/2
    sections:
      pages:
        headline: Events
        info: "{{ page.day.toDate('m.d.Y') }}"
        parent: site.find("events")
        empty: No events yet
        sortBy: day desc
        template: event

      info:
        type: pages
        headline: Info & Index
        status: listed
        image: icon


      

    
      