title: Site

columns:
  left:
    width: 1/2
    sections: 
      listed:
        extends: sections/readings 
        headline: Readings
        limit: 10

  right:
    width: 1/2
    sections:
      pages:
        headline: Annotations
        info: "{{ page.day.toDate('m.d.Y') }}"
        parent: site.find("annotations")
        empty: No annotations
        flip: true
        limit: 10

      info:
        type: pages
        headline: Info & Index
        status: listed
        image: icon


      

    
      